import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1768637568682 implements MigrationInterface {
    name = 'InitialSchema1768637568682'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "genres" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "color" character varying, "isActive" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d1cbe4fe39bdfc77c76e94eada5" UNIQUE ("slug"), CONSTRAINT "PK_80ecd718f0f00dde5d77a9be842" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "moods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "color" character varying, "isActive" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e9d193c85b73adfd7e903acdf15" UNIQUE ("slug"), CONSTRAINT "PK_5e8d7a76ab84b2b527458490774" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."albums_type_enum" AS ENUM('album', 'mixtape', 'ep')`);
        await queryRunner.query(`CREATE TYPE "public"."albums_status_enum" AS ENUM('draft', 'pending', 'approved', 'rejected', 'published', 'hidden')`);
        await queryRunner.query(`CREATE TABLE "albums" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "coverUrl" character varying, "bannerUrl" character varying, "type" "public"."albums_type_enum" NOT NULL DEFAULT 'album', "plays" integer NOT NULL DEFAULT '0', "likes" integer NOT NULL DEFAULT '0', "status" "public"."albums_status_enum" NOT NULL DEFAULT 'draft', "creatorId" uuid, "isOtrPick" boolean NOT NULL DEFAULT false, "isFeatured" boolean NOT NULL DEFAULT false, "publishedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_95d212fead2c16a7b517c8f55fc" UNIQUE ("slug"), CONSTRAINT "PK_838ebae24d2e12082670ffc95d7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."playlists_status_enum" AS ENUM('draft', 'published', 'hidden')`);
        await queryRunner.query(`CREATE TABLE "playlists" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "coverUrl" character varying, "plays" integer NOT NULL DEFAULT '0', "likes" integer NOT NULL DEFAULT '0', "status" "public"."playlists_status_enum" NOT NULL DEFAULT 'draft', "creatorId" uuid, "isOtrPick" boolean NOT NULL DEFAULT false, "isFeatured" boolean NOT NULL DEFAULT false, "publishedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8bc3ed694cc8c188f8c65030c82" UNIQUE ("slug"), CONSTRAINT "PK_a4597f4189a75d20507f3f7ef0d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."songs_status_enum" AS ENUM('draft', 'pending', 'approved', 'rejected', 'published', 'hidden')`);
        await queryRunner.query(`CREATE TABLE "songs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "coverUrl" character varying, "bannerUrl" character varying, "audioUrl" character varying, "duration" character varying, "plays" integer NOT NULL DEFAULT '0', "likes" integer NOT NULL DEFAULT '0', "status" "public"."songs_status_enum" NOT NULL DEFAULT 'draft', "rejectionReason" text, "creatorId" uuid, "reviewedBy" character varying, "reviewedAt" TIMESTAMP, "publishedAt" TIMESTAMP, "isOtrPick" boolean NOT NULL DEFAULT false, "isFeatured" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_56aae0d8ac9db4626985e2257e8" UNIQUE ("slug"), CONSTRAINT "PK_e504ce8ad2e291d3a1d8f1ea2f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('user', 'creator', 'resident', 'admin')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'suspended', 'pending')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "username" character varying NOT NULL, "password" character varying NOT NULL, "displayName" character varying, "bio" text, "avatarUrl" character varying, "bannerUrl" character varying, "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "isVerified" boolean NOT NULL DEFAULT false, "lastActiveAt" TIMESTAMP, "genres" text, "nextShow" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."subscribers_status_enum" AS ENUM('active', 'unsubscribed', 'bounced')`);
        await queryRunner.query(`CREATE TABLE "subscribers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "name" character varying, "status" "public"."subscribers_status_enum" NOT NULL DEFAULT 'active', "source" character varying, "emailsSent" integer NOT NULL DEFAULT '0', "emailsOpened" integer NOT NULL DEFAULT '0', "lastEmailAt" TIMESTAMP, "subscribedAt" TIMESTAMP NOT NULL DEFAULT now(), "unsubscribedAt" TIMESTAMP, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1a7163c08f0e57bd1c9821508b1" UNIQUE ("email"), CONSTRAINT "PK_cbe0a7a9256c826f403c0236b67" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "value" text, "type" character varying, "group" character varying, "description" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c8639b7626fa94ba8265628f214" UNIQUE ("key"), CONSTRAINT "PK_0669fe20e252eb692bf4d344975" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."program_shows_type_enum" AS ENUM('live', 'prerecorded', 'rerun')`);
        await queryRunner.query(`CREATE TABLE "program_shows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "coverUrl" character varying, "dayOfWeek" integer NOT NULL, "startTime" character varying NOT NULL, "endTime" character varying NOT NULL, "type" "public"."program_shows_type_enum" NOT NULL DEFAULT 'live', "isRecurring" boolean NOT NULL DEFAULT true, "hostId" uuid, "genres" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fc4ba1d08b7f249a50fcce2f089" UNIQUE ("slug"), CONSTRAINT "PK_6c3594e38ef173467dca1d4fa86" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "imageUrl" character varying, "price" numeric(10,2) NOT NULL, "shopUrl" character varying, "isActive" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_464f927ae360106b783ed0b4106" UNIQUE ("slug"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."otr_picks_contenttype_enum" AS ENUM('song', 'album', 'playlist', 'mixtape')`);
        await queryRunner.query(`CREATE TABLE "otr_picks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "contentType" "public"."otr_picks_contenttype_enum" NOT NULL, "contentId" character varying NOT NULL, "curatorNote" text, "isActive" boolean NOT NULL DEFAULT true, "isFeatured" boolean NOT NULL DEFAULT false, "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3b28f00c617e498ed30e1a78343" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "listening_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "songId" uuid NOT NULL, "playCount" integer NOT NULL DEFAULT '0', "totalListenedDuration" double precision NOT NULL DEFAULT '0', "lastPosition" double precision NOT NULL DEFAULT '0', "songDuration" double precision, "completed" boolean NOT NULL DEFAULT false, "lastListenedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a6c26e9fbd171c57d0f320300b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_457cb9f7a9aa5b0f99547da7d3" ON "listening_history" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c258e6e1f838d898bb5f9d2c90" ON "listening_history" ("songId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_007a8892f404c0dab2098f7d5e" ON "listening_history" ("userId", "songId") `);
        await queryRunner.query(`CREATE TYPE "public"."events_status_enum" AS ENUM('upcoming', 'ongoing', 'past', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "coverUrl" character varying, "bannerUrl" character varying, "venue" character varying NOT NULL, "address" character varying, "location" character varying NOT NULL, "eventDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP, "time" character varying NOT NULL, "tags" text, "ticketUrl" character varying, "price" character varying, "isFree" boolean NOT NULL DEFAULT false, "status" "public"."events_status_enum" NOT NULL DEFAULT 'upcoming', "lineup" text, "gallery" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_05bd884c03d3f424e2204bd14cd" UNIQUE ("slug"), CONSTRAINT "PK_40731c7151fe4be3116e45ddf73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "album_genres" ("albumId" uuid NOT NULL, "genreId" uuid NOT NULL, CONSTRAINT "PK_710eb085ad969f71c54b7842e0d" PRIMARY KEY ("albumId", "genreId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cb187cfb8f512f37e27cb51e61" ON "album_genres" ("albumId") `);
        await queryRunner.query(`CREATE INDEX "IDX_10aae8ded440e7c96bca9daaa5" ON "album_genres" ("genreId") `);
        await queryRunner.query(`CREATE TABLE "album_moods" ("albumId" uuid NOT NULL, "moodId" uuid NOT NULL, CONSTRAINT "PK_6de949501326f9a9f96cf7ab691" PRIMARY KEY ("albumId", "moodId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_14772739df52d486c29ad14b63" ON "album_moods" ("albumId") `);
        await queryRunner.query(`CREATE INDEX "IDX_53c1c8ea4d59b556a90148311c" ON "album_moods" ("moodId") `);
        await queryRunner.query(`CREATE TABLE "album_songs" ("albumId" uuid NOT NULL, "songId" uuid NOT NULL, CONSTRAINT "PK_90faea9b897bc2812955eb67c53" PRIMARY KEY ("albumId", "songId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3035953fb2c41cf083948362fe" ON "album_songs" ("albumId") `);
        await queryRunner.query(`CREATE INDEX "IDX_31eca7fa78d88c94133efcea25" ON "album_songs" ("songId") `);
        await queryRunner.query(`CREATE TABLE "playlist_genres" ("playlistId" uuid NOT NULL, "genreId" uuid NOT NULL, CONSTRAINT "PK_587d2588207df141c161f601fce" PRIMARY KEY ("playlistId", "genreId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_117bf1a4c23586c728c922a29f" ON "playlist_genres" ("playlistId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c55ec4ac003adfbeb95d681bcd" ON "playlist_genres" ("genreId") `);
        await queryRunner.query(`CREATE TABLE "playlist_moods" ("playlistId" uuid NOT NULL, "moodId" uuid NOT NULL, CONSTRAINT "PK_bf176299c6bee5c33e9044d7215" PRIMARY KEY ("playlistId", "moodId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_83f6d0220e553dbdcb30a4462f" ON "playlist_moods" ("playlistId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ee58321621e3fdca071541be4b" ON "playlist_moods" ("moodId") `);
        await queryRunner.query(`CREATE TABLE "playlist_songs" ("playlistId" uuid NOT NULL, "songId" uuid NOT NULL, CONSTRAINT "PK_2c381af24b3c13d9b25b63c231c" PRIMARY KEY ("playlistId", "songId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b417e94c5022d641c977ef85d8" ON "playlist_songs" ("playlistId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d6a09d42a96563d9d139b5f7fd" ON "playlist_songs" ("songId") `);
        await queryRunner.query(`CREATE TABLE "song_genres" ("songId" uuid NOT NULL, "genreId" uuid NOT NULL, CONSTRAINT "PK_722ca7a7b53120d4fe9e2d504cc" PRIMARY KEY ("songId", "genreId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f611a201a7d790d14b1c71a90b" ON "song_genres" ("songId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8cb94843324244deb861b2ad3e" ON "song_genres" ("genreId") `);
        await queryRunner.query(`CREATE TABLE "song_moods" ("songId" uuid NOT NULL, "moodId" uuid NOT NULL, CONSTRAINT "PK_c268746f9921cde6c8bc774128c" PRIMARY KEY ("songId", "moodId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c46db5975afa8821b960e1620b" ON "song_moods" ("songId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f8c3dcb83630ff224c8df4f2df" ON "song_moods" ("moodId") `);
        await queryRunner.query(`ALTER TABLE "albums" ADD CONSTRAINT "FK_177b69a3af833f1b76f4522c989" FOREIGN KEY ("creatorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "playlists" ADD CONSTRAINT "FK_14bdc074919eefa637f70de8d79" FOREIGN KEY ("creatorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "songs" ADD CONSTRAINT "FK_0783b89974321cca1f7d13566a0" FOREIGN KEY ("creatorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "program_shows" ADD CONSTRAINT "FK_dfd85917d04ae521aeb99323758" FOREIGN KEY ("hostId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "listening_history" ADD CONSTRAINT "FK_457cb9f7a9aa5b0f99547da7d31" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "listening_history" ADD CONSTRAINT "FK_c258e6e1f838d898bb5f9d2c904" FOREIGN KEY ("songId") REFERENCES "songs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "album_genres" ADD CONSTRAINT "FK_cb187cfb8f512f37e27cb51e61f" FOREIGN KEY ("albumId") REFERENCES "albums"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "album_genres" ADD CONSTRAINT "FK_10aae8ded440e7c96bca9daaa54" FOREIGN KEY ("genreId") REFERENCES "genres"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "album_moods" ADD CONSTRAINT "FK_14772739df52d486c29ad14b638" FOREIGN KEY ("albumId") REFERENCES "albums"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "album_moods" ADD CONSTRAINT "FK_53c1c8ea4d59b556a90148311ca" FOREIGN KEY ("moodId") REFERENCES "moods"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "album_songs" ADD CONSTRAINT "FK_3035953fb2c41cf083948362fe5" FOREIGN KEY ("albumId") REFERENCES "albums"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "album_songs" ADD CONSTRAINT "FK_31eca7fa78d88c94133efcea255" FOREIGN KEY ("songId") REFERENCES "songs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "playlist_genres" ADD CONSTRAINT "FK_117bf1a4c23586c728c922a29f7" FOREIGN KEY ("playlistId") REFERENCES "playlists"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "playlist_genres" ADD CONSTRAINT "FK_c55ec4ac003adfbeb95d681bcd0" FOREIGN KEY ("genreId") REFERENCES "genres"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "playlist_moods" ADD CONSTRAINT "FK_83f6d0220e553dbdcb30a4462f9" FOREIGN KEY ("playlistId") REFERENCES "playlists"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "playlist_moods" ADD CONSTRAINT "FK_ee58321621e3fdca071541be4b6" FOREIGN KEY ("moodId") REFERENCES "moods"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "playlist_songs" ADD CONSTRAINT "FK_b417e94c5022d641c977ef85d8b" FOREIGN KEY ("playlistId") REFERENCES "playlists"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "playlist_songs" ADD CONSTRAINT "FK_d6a09d42a96563d9d139b5f7fdf" FOREIGN KEY ("songId") REFERENCES "songs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "song_genres" ADD CONSTRAINT "FK_f611a201a7d790d14b1c71a90b3" FOREIGN KEY ("songId") REFERENCES "songs"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "song_genres" ADD CONSTRAINT "FK_8cb94843324244deb861b2ad3e1" FOREIGN KEY ("genreId") REFERENCES "genres"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "song_moods" ADD CONSTRAINT "FK_c46db5975afa8821b960e1620b3" FOREIGN KEY ("songId") REFERENCES "songs"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "song_moods" ADD CONSTRAINT "FK_f8c3dcb83630ff224c8df4f2dff" FOREIGN KEY ("moodId") REFERENCES "moods"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "song_moods" DROP CONSTRAINT "FK_f8c3dcb83630ff224c8df4f2dff"`);
        await queryRunner.query(`ALTER TABLE "song_moods" DROP CONSTRAINT "FK_c46db5975afa8821b960e1620b3"`);
        await queryRunner.query(`ALTER TABLE "song_genres" DROP CONSTRAINT "FK_8cb94843324244deb861b2ad3e1"`);
        await queryRunner.query(`ALTER TABLE "song_genres" DROP CONSTRAINT "FK_f611a201a7d790d14b1c71a90b3"`);
        await queryRunner.query(`ALTER TABLE "playlist_songs" DROP CONSTRAINT "FK_d6a09d42a96563d9d139b5f7fdf"`);
        await queryRunner.query(`ALTER TABLE "playlist_songs" DROP CONSTRAINT "FK_b417e94c5022d641c977ef85d8b"`);
        await queryRunner.query(`ALTER TABLE "playlist_moods" DROP CONSTRAINT "FK_ee58321621e3fdca071541be4b6"`);
        await queryRunner.query(`ALTER TABLE "playlist_moods" DROP CONSTRAINT "FK_83f6d0220e553dbdcb30a4462f9"`);
        await queryRunner.query(`ALTER TABLE "playlist_genres" DROP CONSTRAINT "FK_c55ec4ac003adfbeb95d681bcd0"`);
        await queryRunner.query(`ALTER TABLE "playlist_genres" DROP CONSTRAINT "FK_117bf1a4c23586c728c922a29f7"`);
        await queryRunner.query(`ALTER TABLE "album_songs" DROP CONSTRAINT "FK_31eca7fa78d88c94133efcea255"`);
        await queryRunner.query(`ALTER TABLE "album_songs" DROP CONSTRAINT "FK_3035953fb2c41cf083948362fe5"`);
        await queryRunner.query(`ALTER TABLE "album_moods" DROP CONSTRAINT "FK_53c1c8ea4d59b556a90148311ca"`);
        await queryRunner.query(`ALTER TABLE "album_moods" DROP CONSTRAINT "FK_14772739df52d486c29ad14b638"`);
        await queryRunner.query(`ALTER TABLE "album_genres" DROP CONSTRAINT "FK_10aae8ded440e7c96bca9daaa54"`);
        await queryRunner.query(`ALTER TABLE "album_genres" DROP CONSTRAINT "FK_cb187cfb8f512f37e27cb51e61f"`);
        await queryRunner.query(`ALTER TABLE "listening_history" DROP CONSTRAINT "FK_c258e6e1f838d898bb5f9d2c904"`);
        await queryRunner.query(`ALTER TABLE "listening_history" DROP CONSTRAINT "FK_457cb9f7a9aa5b0f99547da7d31"`);
        await queryRunner.query(`ALTER TABLE "program_shows" DROP CONSTRAINT "FK_dfd85917d04ae521aeb99323758"`);
        await queryRunner.query(`ALTER TABLE "songs" DROP CONSTRAINT "FK_0783b89974321cca1f7d13566a0"`);
        await queryRunner.query(`ALTER TABLE "playlists" DROP CONSTRAINT "FK_14bdc074919eefa637f70de8d79"`);
        await queryRunner.query(`ALTER TABLE "albums" DROP CONSTRAINT "FK_177b69a3af833f1b76f4522c989"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f8c3dcb83630ff224c8df4f2df"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c46db5975afa8821b960e1620b"`);
        await queryRunner.query(`DROP TABLE "song_moods"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8cb94843324244deb861b2ad3e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f611a201a7d790d14b1c71a90b"`);
        await queryRunner.query(`DROP TABLE "song_genres"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6a09d42a96563d9d139b5f7fd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b417e94c5022d641c977ef85d8"`);
        await queryRunner.query(`DROP TABLE "playlist_songs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee58321621e3fdca071541be4b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_83f6d0220e553dbdcb30a4462f"`);
        await queryRunner.query(`DROP TABLE "playlist_moods"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c55ec4ac003adfbeb95d681bcd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_117bf1a4c23586c728c922a29f"`);
        await queryRunner.query(`DROP TABLE "playlist_genres"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31eca7fa78d88c94133efcea25"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3035953fb2c41cf083948362fe"`);
        await queryRunner.query(`DROP TABLE "album_songs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_53c1c8ea4d59b556a90148311c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14772739df52d486c29ad14b63"`);
        await queryRunner.query(`DROP TABLE "album_moods"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_10aae8ded440e7c96bca9daaa5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb187cfb8f512f37e27cb51e61"`);
        await queryRunner.query(`DROP TABLE "album_genres"`);
        await queryRunner.query(`DROP TABLE "events"`);
        await queryRunner.query(`DROP TYPE "public"."events_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_007a8892f404c0dab2098f7d5e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c258e6e1f838d898bb5f9d2c90"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_457cb9f7a9aa5b0f99547da7d3"`);
        await queryRunner.query(`DROP TABLE "listening_history"`);
        await queryRunner.query(`DROP TABLE "otr_picks"`);
        await queryRunner.query(`DROP TYPE "public"."otr_picks_contenttype_enum"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "program_shows"`);
        await queryRunner.query(`DROP TYPE "public"."program_shows_type_enum"`);
        await queryRunner.query(`DROP TABLE "settings"`);
        await queryRunner.query(`DROP TABLE "subscribers"`);
        await queryRunner.query(`DROP TYPE "public"."subscribers_status_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "songs"`);
        await queryRunner.query(`DROP TYPE "public"."songs_status_enum"`);
        await queryRunner.query(`DROP TABLE "playlists"`);
        await queryRunner.query(`DROP TYPE "public"."playlists_status_enum"`);
        await queryRunner.query(`DROP TABLE "albums"`);
        await queryRunner.query(`DROP TYPE "public"."albums_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."albums_type_enum"`);
        await queryRunner.query(`DROP TABLE "moods"`);
        await queryRunner.query(`DROP TABLE "genres"`);
    }

}
